f = open("MeatAndFish.txt")
ff = open("GrainAndBread.txt")
fff = open("shoppinglist.txt", "at")
fcontent = f.read()
ffcontent = ff.read()
fff.write(fcontent)
fff.write(ffcontent)
f.close()
ff.close()
fff.close()